project:
  type: website

website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
  title: "Power Visual"
  page-navigation: true
  favicon: "logo.png"

  navbar:
    logo: "logo2.png"
    background: "#AF8D2F"
    left:
    - icon: "house-fill"
      href: "index.html"
    - text: "Proposal"
      href: "proposal.html"
    - text: "Poster"
    - text: "Shiny App"
    - text: "Meeting Minutes"
      href: MOM.qmd
    right:
      - icon: github
        href: https://github.com/TasapornV/ISSS608_GroupProject
      - text: "The Team"
        href: about.qmd
format:
  html:
    theme: Lux
    css: styles.css
    toc: true

editor: visual

