project:
  type: website

website:
  comments: 
    utterances: 
      repo: quarto-dev/quarto-web
  title: "ISSS608-VAA"

  navbar:
    left:
    - icon: "house-fill"
      href: "index.html"
    - text: "Proposal"
      href: "proposal.html"
    - text: "Poster"
    - text: "Shiny App"
    - text: "MOM"
      href: MOM.qmd
    right:
      - icon: github
        href: https://github.com/TasapornV/ISSS608-VAA.git
      - text: "about us"
        href: about.qmd
format:
  html:
    theme: Lumen
    css: styles.css
    toc: true

editor: visual

