project:
  type: website

website:
  title: "POWER ANALYTICS"
  page-navigation: true
  favicon: "images/logo1.png"

  navbar:
    logo: "images/nav_logo.png"
    background: "#AF8D2F"
    left:
      - icon: "house-fill"
        text: "home"
        href: "index.html"
      - text: "Project Snapshot"
        href: "proposal.html"
      - text: "Poster"
        href: "poster.html"
      - text: "developer Guideline"
        href: "Shiny_App_G9/Sandbox_cleaned.html"
      - text: "RShiny App"
        href: https://teampoweranalytics.shinyapps.io/Shiny_App_G9/
      - text: "User Guideline for App"
        href: "User guide.html"
    right:
      - icon: github
        href: https://github.com/TasapornV/ISSS608_GroupProject
      - text: "The Team"
        href: about.qmd
format:
  html:
    theme: Lux
    css: styles.css
    toc: true

editor: visual

