project:
  type: website

website:
  title: "Power Visual"
  page-navigation: true
  favicon: "logo1.png"

  navbar:
    logo: "nav_logo.png"
    background: "#AF8D2F"
    left:
      - icon: "house-fill"
        href: "index.html"
      - text: "Project Snapshot"
        href: "proposal.html"
      - text: "Poster"
      - text: "developer Guideline"
        href: "Shiny_App_G9/Sandbox_cleaned.html"
      - text: "RShiny App"
        href: https://teampoweranalytics.shinyapps.io/Shiny_App_G9/
    right:
      - icon: github
        href: https://github.com/TasapornV/ISSS608_GroupProject
      - text: "The Team"
        href: about.qmd
format:
  html:
    theme: Lux
    css: styles.css
    toc: true

editor: visual

