---
title: "Minute of Meeting"
subtitle: "Uncover Singapore electricity consumption"
author: "Tasaporn Visawameteekul, Law Shiang Row, Khoo Wei Lun"
date: "29 March 2023"
date-modified: "`r Sys.Date()`"
affiliation: "SMU MITB"
execute:
  warning: false
  error: false
  message: false
format: 
  html:
    mainfont: system-ui
    fontsize: medium
    code-fold: false
    code-block-border-left: "#63B9A0"
    code-overflow: wrap
    highlight-style: solarized
    page-layout: full
    number-sections: true
    title-block-banner: true
    fig-align: center
    reader-mode: true
---

### **Meeting Minutes 1**

+--------------------------------------------------------------------+
| **Date:** 14 Jan 2023                                              |
|                                                                    |
| **Present**: KHOO Wei Lun, LAW Shiang Rou, Tasaporn VISAWAMETEEKUL |
|                                                                    |
| **Absent**: NIL                                                    |
|                                                                    |
| **Minute taker**: LAW Shiang Rou                                   |
|                                                                    |
| **Objective**: Explore topics and datasets for group project       |
+--------------------------------------------------------------------+

**Discussion Points** 

A few topics and datasets have been considered during the discussion: 

**Energy-related data**  

**Data source:**

-   <https://www.ema.gov.sg/singapore-energy-statistics/>
-   <https://www.singstat.gov.sg/find-data/search-by-theme/industry/energy-and-utilities/latest-data>

**Discussion points:**

-   This website provides statistics on Singapore energy sector, including the energy supply, consumption and prices. 
-   This might be an interesting area of interest both from the supplier and consumer perspective but a valid and strong use case has to be established.

1.  One possible use case is to help carve a plan to encourage energy conservation
2.  We can also consider combining these data with sustainability-related data for more insights.

**Singapore Economy data**

**Discussion points:**

**Data source:** <https://www.singstat.gov.sg/find-data/search-by-theme?theme=economy&type=all>

1.  We can explore some of the Singapore economy data available on Singstats  
2.  We can try think of some fresh perspectives that we can offer using these common data. 

**Ezlink data**

**Data source:** TBC

**Discussion points:**

-   Explore the use of EZlink data to help in planning of public transport route optimization.

**Transformation of Singapore population**

**Data source:** [https://www.singstat.gov.sg](https://www.singstat.gov.sg/)

**Discussion points:**

-   Using the demographic data available on Singstat, we can plot different visualization to showcase the transformation of Singapore population in terms of education level, gender distribution, races, languages, income, consumption preferences and so on.

**Action Items**

1.  All to explore more on above 4 proposed topics or suggest new topic

**Next meeting** 21 Jan 2023

------------------------------------------------------------------------

### Minute of Meeting 2

+-------------------------------------------------------------------------------------+
| **Date:** 28 Jan 2023                                                               |
|                                                                                     |
| **Present**: KHOO Wei Lun, LAW Shiang Rou, Tasaporn VISAWAMETEEKUL                  |
|                                                                                     |
| **Absent**: NIL                                                                     |
|                                                                                     |
| **Minute taker**: KHOO Wei Lun                                                      |
|                                                                                     |
| **Objective**: Reviewing individual ideas from ideation, explore potential spin-off |
+-------------------------------------------------------------------------------------+

**Discussion Points**

Explore ways to spin-off current idea and to discuss

1.  **Visualize Singapore transformation for areas of interests**

-   Such as education, wealth of the city, etc.
-   Potential challenges on predictive
-   Advantage: large dataset and multiple areas to explore 

2.  **Low birth rate** 

-   Find out the cause of low birth rates 
-   Hypothesis: CPI vs Income
-   Potential area
-   Comparison with other countries is also possible (similar traits among with

3.  **Global cost of living**

-   Limited by few input parameters
-   Possible to combine with 'Low birth rate'
-   Not able to standalone

4.  **Twitter topic analysis**

-   Too challenging to visualize

5.  **Next million dollar HDB**

-   Find factors that might be correlated in driving the HDB price up.
-   Explore realis dataset

6.  **Visualisation of election votes of different years**

-   Explore whether demographics
-   Possible but challenging to show how election areas had changed over time
-   Need to find more dataset that can be visualized and correlate.

7.  **Singapore Energy**

-   How energy sources in Singapore have evolved from the past (however, the sources might not have changed significantly over time)
-   Limitation in understanding of how the markets work.

8.  **Waste to Energy**

-   Explore how different wastes had been transformed in Singapore
-   How much waste are Singapore generating in each categories
-   \% of waste being transformed into

9.  **Online Retail**

-   Segmentation of customers
-   Frequent pattern mining

**Choosing of projects**

-   Choosing topics that are more familiar for us (e.g. Singapore)
-   Eliminated
-   twitter topic analysis (not able to visualize)
-   Singapore energy (difficult to understand the mechanism -- no area of expertise in this field in the team)
-   Next million dollar HDB (similar topics had been done previous
-   Final top two ideas selected: Visualisation of election votes of different years and Low birth rate

**Action Items**

1.  Book Prof Kam's time to run through final project ideas.
2.  Find more possible factors that might correlate with election votes/results.
3.  Find dataset on low birth rate for other countries.

**Next meeting** 31 Jan 2023

------------------------------------------------------------------------

### Minute of Meeting 3 (Consultation session)

+------------------------------------------------------------------------------------------+
| **Date:** 31 Jan 2023                                                                    |
|                                                                                          |
| **Present**: KHOO Wei Lun, LAW Shiang Rou, Tasaporn VISAWAMETEEKUL                       |
|                                                                                          |
| **Absent**: NIL                                                                          |
|                                                                                          |
| **Minute taker**: Tasaporn VISAWAMETEEKUL                                                |
|                                                                                          |
| **Objective**: Finalise the topics and dataset to seek for comments/inputs from Prof Kam |
+------------------------------------------------------------------------------------------+

**Discussion Points**

-   Seek for Prof.Kam advice on the problem statement selected and the possible concern on the dataset.

-   Prof's advice: Problem statement is how to make full use of the data to gain insights (for data analyst)

-   The dataset from the competition has some concern about the missing data. Prof recommend using dataset which has rather complete data to build an application.

-   Proposal need to include:

    1.  data visualization sketch

    2.  packages we plan to use

    3.  analysis we plan to do

**Action Items**

1.  Explore DAL and other datasets suggested by Prof Kam

2.  Finalise dataset to move forward with the project

3.  Brainstorm on visual techniques that can be applied or explored

**Next meeting** 4 Feb 2023

------------------------------------------------------------------------

### Minute of Meeting 4

+--------------------------------------------------------------------+
| **Date:** 4 Feb 2023 \|                                            |
|                                                                    |
| **Present**: KHOO Wei Lun, LAW Shiang Rou, Tasaporn VISAWAMETEEKUL |
|                                                                    |
| **Absent**: NIL                                                    |
|                                                                    |
| **Minute taker**: Khoo Wei Lun \|                                  |
|                                                                    |
| **Objective**: To draft an approach for the project \|             |
+--------------------------------------------------------------------+

**Discussion Points**

Create skeleton for project content:

-   Overview of Singapore Electricity

    1.  Establish storyline

    2.  Exploratory data analysis

-   Content

    1.  Keep it open for user exploration

-   Inferential Analysis

    1.  Correlation with consumption: supply, price, planning area characteristics, demographics

    2.  ANOVA by months, regions, type of dwellings

-   Electricity consumption pattern clustering

    1.  Electricity consumption pattern clustering

    2.  Spatial clustering - patterns of consumption, dwelling type, overall country

    3.  Temporal clustering - grouping months by power consumption

-   Forecasting

    1.  Prediction on price, consumption and supply

    2.  Time series forecasting (ARIMA, ETS -- enable selection)

**Action Items**

1.  Create shared git repository for the project

2.  Sketch visualisation designs

3.  Create first draft for proposal

**Next meeting** 11 Feb 2023
